/**
 * Correlation between main-process tab records and renderer-created `<webview>` guests.
 *
 * With a `<webview>` the renderer owns element creation, so main learns about a
 * guest only when the renderer reports it. That report nominates a
 * `tabId -> webContentsId` mapping, which makes it the one place where a renderer
 * bug — or a compromised renderer — could bind one agent's CDP target to another
 * agent's page. Scope checks downstream cannot catch that: they validate the
 * scope recorded on the tab, not the identity of the WebContents behind it.
 *
 * Every registration is therefore checked against a per-tab nonce, an
 * inspection of the guest itself, and a uniqueness constraint. A binding is
 * made once and never silently changed.
 *
 * Electron lookups are injected so the state machine can be tested without it.
 */

export interface GuestCandidate {
  /** Must be the host renderer that owns this runtime — the check that keeps agents out of the app UI. */
  hostWebContentsId: number | undefined;
  /** Electron reports "webview" for guests; anything else is a different kind of contents. */
  type: string;
  /** Compared against the browser partition so a guest cannot smuggle in another session. */
  partition: string | undefined;
  destroyed: boolean;
}

export interface GuestRegistryOptions {
  /**
   * Resolves a webContents id to the facts needed to validate it, or undefined
   * if it does not exist. `expected` is the jar this tab was promised: Electron
   * will not name a session's partition, so the only check available is asking
   * whether it is that one.
   */
  inspect: (webContentsId: number, expected: string) => GuestCandidate | undefined;
  /** The renderer that is allowed to nominate guests. */
  hostWebContentsId: () => number;
  layerTimeoutMs?: number;
  guestTimeoutMs?: number;
  setTimer?: (callback: () => void, ms: number) => unknown;
  clearTimer?: (handle: unknown) => void;
}

interface PendingGuest {
  nonce: string;
  /** 这张标签页所属的 cookie jar：一个工作区一份，所以按标签页记，不按窗口记。 */
  partition: string;
  resolve: (webContentsId: number) => void;
  reject: (error: Error) => void;
  timer: unknown;
}

export const DEFAULT_LAYER_TIMEOUT_MS = 15_000;
export const DEFAULT_GUEST_TIMEOUT_MS = 10_000;

export class BrowserGuestRegistry {
  private readonly pending = new Map<string, PendingGuest>();
  private readonly bindings = new Map<string, number>();
  private readonly boundGuestIds = new Map<number, string>();
  private readonly layerWaiters = new Set<{ resolve: () => void; reject: (error: Error) => void; timer: unknown }>();
  /** 用户接管 Agent 标签页时，等主进程在 did-attach 里直接认领的那个 guest。 */
  private readonly restores = new Map<string, Omit<PendingGuest, "nonce">>();
  /** 已经认领、但渲染层还没用 nonce 登记确认的 guest。 */
  private readonly claimed = new Map<string, number>();
  private layerReady = false;
  private disposed = false;

  private readonly inspect: GuestRegistryOptions["inspect"];
  private readonly hostWebContentsId: GuestRegistryOptions["hostWebContentsId"];
  private readonly layerTimeoutMs: number;
  private readonly guestTimeoutMs: number;
  private readonly setTimer: (callback: () => void, ms: number) => unknown;
  private readonly clearTimer: (handle: unknown) => void;

  constructor(options: GuestRegistryOptions) {
    this.inspect = options.inspect;
    this.hostWebContentsId = options.hostWebContentsId;
    this.layerTimeoutMs = options.layerTimeoutMs ?? DEFAULT_LAYER_TIMEOUT_MS;
    this.guestTimeoutMs = options.guestTimeoutMs ?? DEFAULT_GUEST_TIMEOUT_MS;
    this.setTimer = options.setTimer ?? ((callback, ms) => setTimeout(callback, ms));
    this.clearTimer = options.clearTimer ?? ((handle) => clearTimeout(handle as ReturnType<typeof setTimeout>));
  }

  /** The renderer's guest layer has mounted and is able to create elements. */
  markLayerReady(): void {
    if (this.layerReady) return;
    this.layerReady = true;
    for (const waiter of this.layerWaiters) {
      this.clearTimer(waiter.timer);
      waiter.resolve();
    }
    this.layerWaiters.clear();
  }

  /** A renderer reload tears down every guest, so the layer must announce itself again. */
  markLayerGone(): void {
    this.layerReady = false;
  }

  isLayerReady(): boolean {
    return this.layerReady;
  }

  waitForLayer(): Promise<void> {
    if (this.disposed) return Promise.reject(new Error("CoilCoil 正在关闭。"));
    if (this.layerReady) return Promise.resolve();
    return new Promise<void>((resolve, reject) => {
      const waiter = {
        resolve,
        reject,
        timer: this.setTimer(() => {
          this.layerWaiters.delete(waiter);
          reject(new Error("内置浏览器视图未就绪。"));
        }, this.layerTimeoutMs),
      };
      this.layerWaiters.add(waiter);
    });
  }

  /**
   * Begin waiting for the renderer to report the guest it created for this tab.
   * The nonce is generated by the caller and travels with the roster entry, so a
   * stale report from a previous element cannot satisfy a newer request.
   */
  expectGuest(tabId: string, nonce: string, partition: string): Promise<number> {
    if (this.disposed) return Promise.reject(new Error("CoilCoil 正在关闭。"));
    if (this.pending.has(tabId)) return Promise.reject(new Error(`标签页 ${tabId} 已在等待浏览器视图。`));
    return new Promise<number>((resolve, reject) => {
      const entry: PendingGuest = {
        nonce,
        partition,
        resolve,
        reject,
        timer: this.setTimer(() => {
          this.pending.delete(tabId);
          reject(new Error("内置浏览器视图创建超时。"));
        }, this.guestTimeoutMs),
      };
      this.pending.set(tabId, entry);
    });
  }

  /**
   * Validate a renderer-nominated mapping and settle the pending request.
   * Throws — never silently ignores — so the renderer can drop the element it
   * created instead of leaving an orphaned guest alive.
   */
  register(tabId: string, nonce: string, webContentsId: number): void {
    const entry = this.pending.get(tabId);
    // Covers an unknown tab, a tab closed while its guest was in flight, and a
    // report that arrived after the timeout already purged the request.
    if (!entry) throw new Error(`未在等待标签页 ${tabId} 的浏览器视图。`);
    if (entry.nonce !== nonce) throw new Error(`标签页 ${tabId} 的浏览器视图校验失败。`);
    if (!Number.isInteger(webContentsId) || webContentsId <= 0) {
      throw new Error(`标签页 ${tabId} 的浏览器视图标识无效。`);
    }

    // 接管时主进程已经先认领了一个 guest：渲染层报上来的必须就是那一个。
    const claimed = this.claimed.get(tabId);
    if (claimed !== undefined && claimed !== webContentsId) throw new Error(`标签页 ${tabId} 的浏览器视图和认领的不一致。`);

    const owner = this.boundGuestIds.get(webContentsId);
    // The load-bearing check against cross-scope cross-wiring: one guest may back
    // exactly one tab, so a second tab can never be pointed at a live page.
    if (owner !== undefined) throw new Error(`浏览器视图 ${webContentsId} 已绑定到其他标签页。`);

    const candidate = this.inspect(webContentsId, entry.partition);
    if (!candidate || candidate.destroyed) throw new Error(`浏览器视图 ${webContentsId} 不存在。`);
    if (candidate.type !== "webview") throw new Error(`浏览器视图 ${webContentsId} 类型不符。`);
    if (candidate.hostWebContentsId !== this.hostWebContentsId()) {
      throw new Error(`浏览器视图 ${webContentsId} 不属于当前窗口。`);
    }
    if (candidate.partition !== entry.partition) {
      throw new Error(`浏览器视图 ${webContentsId} 会话分区不符。`);
    }

    this.clearTimer(entry.timer);
    this.pending.delete(tabId);
    this.claimed.delete(tabId);
    this.bindings.set(tabId, webContentsId);
    this.boundGuestIds.set(webContentsId, tabId);
    entry.resolve(webContentsId);
  }

  /**
   * 用户接管 Agent 标签页：等这张标签页的元素挂上。
   *
   * 这种元素什么都不加载（主进程要往里恢复页面状态），所以等不到 dom-ready 之后的
   * 常规登记；主进程在 did-attach-webview 里直接认领它（claimRestore），恢复完页面、
   * 渲染层再照常用 nonce 登记，register 会核对报上来的就是认领的那一个。
   */
  expectRestoreGuest(tabId: string, partition: string): Promise<number> {
    if (this.disposed) return Promise.reject(new Error("CoilCoil 正在关闭。"));
    if (this.restores.has(tabId)) return Promise.reject(new Error(`标签页 ${tabId} 已在等待接管。`));
    return new Promise<number>((resolve, reject) => {
      this.restores.set(tabId, {
        partition,
        resolve,
        reject,
        timer: this.setTimer(() => {
          this.restores.delete(tabId);
          reject(new Error("接管标签页超时。"));
        }, this.guestTimeoutMs),
      });
    });
  }

  /** will-attach-webview 里问：这个带接管标记的元素，是不是真有一张标签页在等。 */
  acceptsRestore(tabId: string, partition: unknown): boolean {
    return this.restores.get(tabId)?.partition === partition;
  }

  restorePending(tabId: string): boolean {
    return this.restores.has(tabId);
  }

  /** did-attach-webview 里认领：和 register 同一套核对，只是不等 nonce（稍后 register 补上）。 */
  claimRestore(tabId: string, webContentsId: number): void {
    const entry = this.restores.get(tabId);
    if (!entry) throw new Error(`未在等待接管标签页 ${tabId}。`);
    const fail = (message: string): never => {
      this.clearTimer(entry.timer);
      this.restores.delete(tabId);
      const error = new Error(message);
      entry.reject(error);
      throw error;
    };
    if (this.boundGuestIds.has(webContentsId)) fail(`浏览器视图 ${webContentsId} 已绑定到其他标签页。`);
    const candidate = this.inspect(webContentsId, entry.partition);
    if (!candidate || candidate.destroyed) fail(`浏览器视图 ${webContentsId} 不存在。`);
    if (candidate!.type !== "webview") fail(`浏览器视图 ${webContentsId} 类型不符。`);
    if (candidate!.hostWebContentsId !== this.hostWebContentsId()) fail(`浏览器视图 ${webContentsId} 不属于当前窗口。`);
    if (candidate!.partition !== entry.partition) fail(`浏览器视图 ${webContentsId} 会话分区不符。`);
    this.clearTimer(entry.timer);
    this.restores.delete(tabId);
    this.claimed.set(tabId, webContentsId);
    entry.resolve(webContentsId);
  }

  /** The renderer could not create the element; fail the wait rather than let it time out. */
  fail(tabId: string, nonce: string, reason: string): void {
    const entry = this.pending.get(tabId);
    if (!entry || entry.nonce !== nonce) return;
    this.clearTimer(entry.timer);
    this.pending.delete(tabId);
    entry.reject(new Error(`内置浏览器视图创建失败：${reason}`));
  }

  /** Drop a tab's reservation and binding. Safe to call for tabs that never attached. */
  release(tabId: string): void {
    const entry = this.pending.get(tabId);
    if (entry) {
      this.clearTimer(entry.timer);
      this.pending.delete(tabId);
      entry.reject(new Error("标签页已关闭。"));
    }
    const restore = this.restores.get(tabId);
    if (restore) {
      this.clearTimer(restore.timer);
      this.restores.delete(tabId);
      restore.reject(new Error("标签页已关闭。"));
    }
    this.claimed.delete(tabId);
    const webContentsId = this.bindings.get(tabId);
    if (webContentsId !== undefined) {
      this.bindings.delete(tabId);
      this.boundGuestIds.delete(webContentsId);
    }
  }

  boundGuestId(tabId: string): number | undefined {
    return this.bindings.get(tabId);
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    for (const [tabId, entry] of this.pending) {
      this.clearTimer(entry.timer);
      entry.reject(new Error("CoilCoil 正在关闭。"));
      this.pending.delete(tabId);
    }
    for (const [tabId, entry] of this.restores) {
      this.clearTimer(entry.timer);
      entry.reject(new Error("CoilCoil 正在关闭。"));
      this.restores.delete(tabId);
    }
    this.claimed.clear();
    for (const waiter of this.layerWaiters) {
      this.clearTimer(waiter.timer);
      waiter.reject(new Error("CoilCoil 正在关闭。"));
    }
    this.layerWaiters.clear();
    this.bindings.clear();
    this.boundGuestIds.clear();
    this.layerReady = false;
  }
}
